"""initial_migration
Revision ID: fe8a354cb79a
Revises: None
Create Date: 2026-04-19 22:12:05.057369
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe8a354cb79a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('clinic_type', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_clinics_parent_id_tbl_clinics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_clinics'))
    )
    op.create_index(op.f('ix_tbl_clinics_code'), 'tbl_clinics', ['code'], unique=True)
    op.create_index(op.f('ix_tbl_clinics_email'), 'tbl_clinics', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_clinics_id'), 'tbl_clinics', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_clinics_name'), 'tbl_clinics', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_clinics_parent_id'), 'tbl_clinics', ['parent_id'], unique=False)
    op.create_table('tbl_medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('pack_size', sa.String(length=50), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('controlled', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_medicines'))
    )
    op.create_index('ix_medicines_brand_strength', 'tbl_medicines', ['brand_name', 'strength'], unique=False)
    op.create_index(op.f('ix_tbl_medicines_brand_name'), 'tbl_medicines', ['brand_name'], unique=False)
    op.create_index(op.f('ix_tbl_medicines_generic_name'), 'tbl_medicines', ['generic_name'], unique=False)
    op.create_index(op.f('ix_tbl_medicines_id'), 'tbl_medicines', ['id'], unique=False)
    op.create_table('tbl_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_permissions'))
    )
    op.create_index(op.f('ix_tbl_permissions_id'), 'tbl_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_permissions_name'), 'tbl_permissions', ['name'], unique=True)
    op.create_table('tbl_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowed_doctors', sa.Integer(), nullable=False),
    sa.Column('allowed_receptionists', sa.Integer(), nullable=False),
    sa.Column('allowed_branches', sa.Integer(), nullable=False),
    sa.Column('max_appointments_per_day', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_tbl_plans_name'))
    )
    op.create_index(op.f('ix_tbl_plans_id'), 'tbl_plans', ['id'], unique=False)
    op.create_table('tbl_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_roles'))
    )
    op.create_index(op.f('ix_tbl_roles_id'), 'tbl_roles', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_roles_name'), 'tbl_roles', ['name'], unique=True)
    op.create_table('tbl_service_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_service_codes'))
    )
    op.create_index(op.f('ix_tbl_service_codes_code'), 'tbl_service_codes', ['code'], unique=True)
    op.create_index(op.f('ix_tbl_service_codes_id'), 'tbl_service_codes', ['id'], unique=False)
    op.create_table('tbl_inventory_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_level', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_inventory_stock_clinic_id_tbl_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['tbl_medicines.id'], name=op.f('fk_tbl_inventory_stock_medicine_id_tbl_medicines'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_inventory_stock'))
    )
    op.create_index('ix_inventory_stock_clinic_medicine', 'tbl_inventory_stock', ['clinic_id', 'medicine_id'], unique=False)
    op.create_index(op.f('ix_tbl_inventory_stock_clinic_id'), 'tbl_inventory_stock', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_inventory_stock_id'), 'tbl_inventory_stock', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_inventory_stock_medicine_id'), 'tbl_inventory_stock', ['medicine_id'], unique=False)
    op.create_table('tbl_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['tbl_permissions.id'], name=op.f('fk_tbl_role_permissions_permission_id_tbl_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], name=op.f('fk_tbl_role_permissions_role_id_tbl_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_role_permissions'))
    )
    op.create_index(op.f('ix_tbl_role_permissions_id'), 'tbl_role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_role_permissions_permission_id'), 'tbl_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_tbl_role_permissions_role_id'), 'tbl_role_permissions', ['role_id'], unique=False)
    op.create_table('tbl_system_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_system_preferences_clinic_id_tbl_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_system_preferences'))
    )
    op.create_index(op.f('ix_tbl_system_preferences_clinic_id'), 'tbl_system_preferences', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_system_preferences_id'), 'tbl_system_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_system_preferences_key'), 'tbl_system_preferences', ['key'], unique=False)
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], name=op.f('fk_tbl_users_role_id_tbl_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_users'))
    )
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_users_id'), 'tbl_users', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_users_role_id'), 'tbl_users', ['role_id'], unique=False)
    op.create_table('tbl_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_admins_clinic_id_tbl_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_admins_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_admins'))
    )
    op.create_index(op.f('ix_tbl_admins_clinic_id'), 'tbl_admins', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_admins_email'), 'tbl_admins', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_admins_id'), 'tbl_admins', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_admins_user_id'), 'tbl_admins', ['user_id'], unique=False)
    op.create_table('tbl_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_table', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('s3_key', sa.String(length=2048), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['tbl_users.id'], name=op.f('fk_tbl_attachments_uploaded_by_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_attachments'))
    )
    op.create_index(op.f('ix_tbl_attachments_id'), 'tbl_attachments', ['id'], unique=False)
    op.create_table('tbl_audit_deletions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('row_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('export_path', sa.String(length=1024), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['tbl_users.id'], name=op.f('fk_tbl_audit_deletions_actor_id_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_audit_deletions'))
    )
    op.create_index(op.f('ix_tbl_audit_deletions_id'), 'tbl_audit_deletions', ['id'], unique=False)
    op.create_table('tbl_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['tbl_users.id'], name=op.f('fk_tbl_audit_logs_actor_id_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_audit_logs'))
    )
    op.create_index(op.f('ix_tbl_audit_logs_id'), 'tbl_audit_logs', ['id'], unique=False)
    op.create_table('tbl_doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_bookings', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_registration_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_doctors_clinic_id_tbl_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['tbl_plans.id'], name=op.f('fk_tbl_doctors_plan_id_tbl_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_doctors_user_id_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_doctors'))
    )
    op.create_index(op.f('ix_tbl_doctors_clinic_id'), 'tbl_doctors', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_doctors_email'), 'tbl_doctors', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_doctors_id'), 'tbl_doctors', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_doctors_medical_registration_number'), 'tbl_doctors', ['medical_registration_number'], unique=False)
    op.create_index(op.f('ix_tbl_doctors_name'), 'tbl_doctors', ['name'], unique=False)
    op.create_index(op.f('ix_tbl_doctors_user_id'), 'tbl_doctors', ['user_id'], unique=False)
    op.create_table('tbl_inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference_table', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_users.id'], name=op.f('fk_tbl_inventory_movements_created_by_tbl_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['tbl_inventory_stock.id'], name=op.f('fk_tbl_inventory_movements_stock_id_tbl_inventory_stock'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_inventory_movements'))
    )
    op.create_index(op.f('ix_tbl_inventory_movements_id'), 'tbl_inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_inventory_movements_stock_id'), 'tbl_inventory_movements', ['stock_id'], unique=False)
    op.create_table('tbl_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('cnic', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_patients_clinic_id_tbl_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_patients_user_id_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_patients'))
    )
    op.create_index(op.f('ix_tbl_patients_clinic_id'), 'tbl_patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_patients_cnic'), 'tbl_patients', ['cnic'], unique=True)
    op.create_index(op.f('ix_tbl_patients_id'), 'tbl_patients', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_patients_medical_record_number'), 'tbl_patients', ['medical_record_number'], unique=False)
    op.create_index(op.f('ix_tbl_patients_phone'), 'tbl_patients', ['phone'], unique=False)
    op.create_index(op.f('ix_tbl_patients_user_id'), 'tbl_patients', ['user_id'], unique=False)
    op.create_table('tbl_receptionists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_receptionists_clinic_id_tbl_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_receptionists_user_id_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_receptionists'))
    )
    op.create_index(op.f('ix_tbl_receptionists_clinic_id'), 'tbl_receptionists', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_receptionists_email'), 'tbl_receptionists', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_receptionists_id'), 'tbl_receptionists', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_receptionists_user_id'), 'tbl_receptionists', ['user_id'], unique=False)
    op.create_table('tbl_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], name=op.f('fk_tbl_user_roles_role_id_tbl_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_user_roles_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_user_roles'))
    )
    op.create_index(op.f('ix_tbl_user_roles_id'), 'tbl_user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_roles_role_id'), 'tbl_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_tbl_user_roles_user_id'), 'tbl_user_roles', ['user_id'], unique=False)
    op.create_table('tbl_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('receptionist_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('no_show', sa.Boolean(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'booked'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canceled_by'], ['tbl_users.id'], name=op.f('fk_tbl_appointments_canceled_by_tbl_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_appointments_clinic_id_tbl_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_users.id'], name=op.f('fk_tbl_appointments_created_by_tbl_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['tbl_doctors.id'], name=op.f('fk_tbl_appointments_doctor_id_tbl_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['tbl_patients.id'], name=op.f('fk_tbl_appointments_patient_id_tbl_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receptionist_id'], ['tbl_receptionists.id'], name=op.f('fk_tbl_appointments_receptionist_id_tbl_receptionists'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_appointments'))
    )
    op.create_index('ix_appointments_clinic_date_time', 'tbl_appointments', ['clinic_id', 'date', 'time'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_booking_reference'), 'tbl_appointments', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_tbl_appointments_clinic_id'), 'tbl_appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_created_by'), 'tbl_appointments', ['created_by'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_date'), 'tbl_appointments', ['date'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_doctor_id'), 'tbl_appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_id'), 'tbl_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_patient_id'), 'tbl_appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tbl_appointments_receptionist_id'), 'tbl_appointments', ['receptionist_id'], unique=False)
    op.create_table('tbl_doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_doctor_availability_clinic_id_tbl_clinics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['tbl_doctors.id'], name=op.f('fk_tbl_doctor_availability_doctor_id_tbl_doctors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_doctor_availability'))
    )
    op.create_index(op.f('ix_tbl_doctor_availability_clinic_id'), 'tbl_doctor_availability', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_doctor_availability_doctor_id'), 'tbl_doctor_availability', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_tbl_doctor_availability_id'), 'tbl_doctor_availability', ['id'], unique=False)
    op.create_table('tbl_medicine_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by_doctor_id', sa.Integer(), nullable=True),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_medicine_requests_clinic_id_tbl_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_doctor_id'], ['tbl_doctors.id'], name=op.f('fk_tbl_medicine_requests_requested_by_doctor_id_tbl_doctors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['tbl_users.id'], name=op.f('fk_tbl_medicine_requests_reviewed_by_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_medicine_requests'))
    )
    op.create_index(op.f('ix_tbl_medicine_requests_clinic_id'), 'tbl_medicine_requests', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_medicine_requests_id'), 'tbl_medicine_requests', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_medicine_requests_requested_by_doctor_id'), 'tbl_medicine_requests', ['requested_by_doctor_id'], unique=False)
    op.create_table('tbl_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['tbl_patients.id'], name=op.f('fk_tbl_notifications_patient_id_tbl_patients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_notifications_user_id_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_notifications'))
    )
    op.create_index(op.f('ix_tbl_notifications_id'), 'tbl_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_notifications_patient_id'), 'tbl_notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tbl_notifications_user_id'), 'tbl_notifications', ['user_id'], unique=False)
    op.create_table('tbl_appointment_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('service_code_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['tbl_appointments.id'], name=op.f('fk_tbl_appointment_services_appointment_id_tbl_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_code_id'], ['tbl_service_codes.id'], name=op.f('fk_tbl_appointment_services_service_code_id_tbl_service_codes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_appointment_services'))
    )
    op.create_index(op.f('ix_tbl_appointment_services_appointment_id'), 'tbl_appointment_services', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_tbl_appointment_services_id'), 'tbl_appointment_services', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_appointment_services_service_code_id'), 'tbl_appointment_services', ['service_code_id'], unique=False)
    op.create_table('tbl_patient_vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('blood_sugar', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('taken_by', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['tbl_appointments.id'], name=op.f('fk_tbl_patient_vitals_appointment_id_tbl_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['tbl_patients.id'], name=op.f('fk_tbl_patient_vitals_patient_id_tbl_patients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taken_by'], ['tbl_users.id'], name=op.f('fk_tbl_patient_vitals_taken_by_tbl_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_patient_vitals'))
    )
    op.create_index(op.f('ix_tbl_patient_vitals_appointment_id'), 'tbl_patient_vitals', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_tbl_patient_vitals_id'), 'tbl_patient_vitals', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_patient_vitals_patient_id'), 'tbl_patient_vitals', ['patient_id'], unique=False)
    op.create_table('tbl_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('receptionist_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_provider', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=50), server_default=sa.text("'success'"), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['tbl_appointments.id'], name=op.f('fk_tbl_payment_transactions_appointment_id_tbl_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_payment_transactions_clinic_id_tbl_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['tbl_doctors.id'], name=op.f('fk_tbl_payment_transactions_doctor_id_tbl_doctors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['tbl_patients.id'], name=op.f('fk_tbl_payment_transactions_patient_id_tbl_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receptionist_id'], ['tbl_receptionists.id'], name=op.f('fk_tbl_payment_transactions_receptionist_id_tbl_receptionists'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_payment_transactions'))
    )
    op.create_index(op.f('ix_tbl_payment_transactions_appointment_id'), 'tbl_payment_transactions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_tbl_payment_transactions_clinic_id'), 'tbl_payment_transactions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_payment_transactions_doctor_id'), 'tbl_payment_transactions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_tbl_payment_transactions_id'), 'tbl_payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_payment_transactions_patient_id'), 'tbl_payment_transactions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tbl_payment_transactions_receptionist_id'), 'tbl_payment_transactions', ['receptionist_id'], unique=False)
    op.create_index(op.f('ix_tbl_payment_transactions_transaction_reference'), 'tbl_payment_transactions', ['transaction_reference'], unique=False)
    op.create_table('tbl_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes_for_patient', sa.Text(), nullable=True),
    sa.Column('prescription_number', sa.String(length=100), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('signature_hash', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['tbl_appointments.id'], name=op.f('fk_tbl_prescriptions_appointment_id_tbl_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_prescriptions_clinic_id_tbl_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['tbl_doctors.id'], name=op.f('fk_tbl_prescriptions_doctor_id_tbl_doctors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['tbl_users.id'], name=op.f('fk_tbl_prescriptions_issued_by_user_id_tbl_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['tbl_patients.id'], name=op.f('fk_tbl_prescriptions_patient_id_tbl_patients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_prescriptions'))
    )
    op.create_index(op.f('ix_tbl_prescriptions_appointment_id'), 'tbl_prescriptions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_tbl_prescriptions_clinic_id'), 'tbl_prescriptions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_prescriptions_doctor_id'), 'tbl_prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_tbl_prescriptions_id'), 'tbl_prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_prescriptions_patient_id'), 'tbl_prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tbl_prescriptions_prescription_number'), 'tbl_prescriptions', ['prescription_number'], unique=True)
    op.create_table('tbl_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'unpaid'"), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('pdf_s3_key', sa.String(length=2048), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['tbl_appointments.id'], name=op.f('fk_tbl_invoices_appointment_id_tbl_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['tbl_clinics.id'], name=op.f('fk_tbl_invoices_clinic_id_tbl_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by'], ['tbl_users.id'], name=op.f('fk_tbl_invoices_issued_by_tbl_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['tbl_payment_transactions.id'], name=op.f('fk_tbl_invoices_payment_id_tbl_payment_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_invoices'))
    )
    op.create_index(op.f('ix_tbl_invoices_clinic_id'), 'tbl_invoices', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_tbl_invoices_id'), 'tbl_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_invoices_invoice_number'), 'tbl_invoices', ['invoice_number'], unique=True)
    op.create_table('tbl_prescription_medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dispensed_quantity', sa.Integer(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispensed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispensed_by'], ['tbl_users.id'], name=op.f('fk_tbl_prescription_medicines_dispensed_by_tbl_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['tbl_medicines.id'], name=op.f('fk_tbl_prescription_medicines_medicine_id_tbl_medicines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['tbl_prescriptions.id'], name=op.f('fk_tbl_prescription_medicines_prescription_id_tbl_prescriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_prescription_medicines'))
    )
    op.create_index(op.f('ix_tbl_prescription_medicines_id'), 'tbl_prescription_medicines', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_prescription_medicines_medicine_id'), 'tbl_prescription_medicines', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_tbl_prescription_medicines_prescription_id'), 'tbl_prescription_medicines', ['prescription_id'], unique=False)
    op.execute("DROP TABLE IF EXISTS doctors CASCADE")
    op.execute("DROP TABLE IF EXISTS doctor_availability CASCADE")
    op.execute("DROP TABLE IF EXISTS clinics CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS invoices CASCADE")
    op.execute("DROP TABLE IF EXISTS patients CASCADE")
    op.execute("DROP TABLE IF EXISTS system_preferences CASCADE")
    op.execute("DROP TABLE IF EXISTS payment_transactions CASCADE")
    op.execute("DROP TABLE IF EXISTS admins CASCADE")
    op.execute("DROP TABLE IF EXISTS receptionists CASCADE")
    op.execute("DROP TABLE IF EXISTS appointments CASCADE")
    op.execute("DROP TABLE IF EXISTS plans CASCADE")
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('allowed_doctors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allowed_receptionists', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allowed_branches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_appointments_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validity_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey')),
    sa.UniqueConstraint('name', name=op.f('plans_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receptionist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('appointments_clinic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('appointments_doctor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receptionist_id'], ['receptionists.id'], name=op.f('appointments_receptionist_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_table('receptionists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('receptionists_clinic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('receptionists_pkey'))
    )
    op.create_index(op.f('ix_receptionists_id'), 'receptionists', ['id'], unique=False)
    op.create_index(op.f('ix_receptionists_email'), 'receptionists', ['email'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('admins_clinic_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey'))
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('payment_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receptionist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('payment_transactions_appointment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('payment_transactions_clinic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('payment_transactions_doctor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('payment_transactions_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receptionist_id'], ['receptionists.id'], name=op.f('payment_transactions_receptionist_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_transactions_pkey'))
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_table('system_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('system_preferences_clinic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('system_preferences_pkey'))
    )
    op.create_index(op.f('ix_system_preferences_key'), 'system_preferences', ['key'], unique=False)
    op.create_index(op.f('ix_system_preferences_id'), 'system_preferences', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cnic', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('patients_clinic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_cnic'), 'patients', ['cnic'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('invoices_appointment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_transactions.id'], name=op.f('invoices_payment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clinics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['clinics.id'], name=op.f('clinics_parent_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('clinics_pkey'))
    )
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_index(op.f('ix_clinics_code'), 'clinics', ['code'], unique=True)
    op.create_table('doctor_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('doctor_availability_clinic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_availability_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_availability_pkey'))
    )
    op.create_index(op.f('ix_doctor_availability_id'), 'doctor_availability', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_concurrent_bookings', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('doctors_clinic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('doctors_plan_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctors_pkey'))
    )
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.drop_index(op.f('ix_tbl_prescription_medicines_prescription_id'), table_name='tbl_prescription_medicines')
    op.drop_index(op.f('ix_tbl_prescription_medicines_medicine_id'), table_name='tbl_prescription_medicines')
    op.drop_index(op.f('ix_tbl_prescription_medicines_id'), table_name='tbl_prescription_medicines')
    op.drop_table('tbl_prescription_medicines')
    op.drop_index(op.f('ix_tbl_invoices_invoice_number'), table_name='tbl_invoices')
    op.drop_index(op.f('ix_tbl_invoices_id'), table_name='tbl_invoices')
    op.drop_index(op.f('ix_tbl_invoices_clinic_id'), table_name='tbl_invoices')
    op.drop_table('tbl_invoices')
    op.drop_index(op.f('ix_tbl_prescriptions_prescription_number'), table_name='tbl_prescriptions')
    op.drop_index(op.f('ix_tbl_prescriptions_patient_id'), table_name='tbl_prescriptions')
    op.drop_index(op.f('ix_tbl_prescriptions_id'), table_name='tbl_prescriptions')
    op.drop_index(op.f('ix_tbl_prescriptions_doctor_id'), table_name='tbl_prescriptions')
    op.drop_index(op.f('ix_tbl_prescriptions_clinic_id'), table_name='tbl_prescriptions')
    op.drop_index(op.f('ix_tbl_prescriptions_appointment_id'), table_name='tbl_prescriptions')
    op.drop_table('tbl_prescriptions')
    op.drop_index(op.f('ix_tbl_payment_transactions_transaction_reference'), table_name='tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_payment_transactions_receptionist_id'), table_name='tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_payment_transactions_patient_id'), table_name='tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_payment_transactions_id'), table_name='tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_payment_transactions_doctor_id'), table_name='tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_payment_transactions_clinic_id'), table_name='tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_payment_transactions_appointment_id'), table_name='tbl_payment_transactions')
    op.drop_table('tbl_payment_transactions')
    op.drop_index(op.f('ix_tbl_patient_vitals_patient_id'), table_name='tbl_patient_vitals')
    op.drop_index(op.f('ix_tbl_patient_vitals_id'), table_name='tbl_patient_vitals')
    op.drop_index(op.f('ix_tbl_patient_vitals_appointment_id'), table_name='tbl_patient_vitals')
    op.drop_table('tbl_patient_vitals')
    op.drop_index(op.f('ix_tbl_appointment_services_service_code_id'), table_name='tbl_appointment_services')
    op.drop_index(op.f('ix_tbl_appointment_services_id'), table_name='tbl_appointment_services')
    op.drop_index(op.f('ix_tbl_appointment_services_appointment_id'), table_name='tbl_appointment_services')
    op.drop_table('tbl_appointment_services')
    op.drop_index(op.f('ix_tbl_notifications_user_id'), table_name='tbl_notifications')
    op.drop_index(op.f('ix_tbl_notifications_patient_id'), table_name='tbl_notifications')
    op.drop_index(op.f('ix_tbl_notifications_id'), table_name='tbl_notifications')
    op.drop_table('tbl_notifications')
    op.drop_index(op.f('ix_tbl_medicine_requests_requested_by_doctor_id'), table_name='tbl_medicine_requests')
    op.drop_index(op.f('ix_tbl_medicine_requests_id'), table_name='tbl_medicine_requests')
    op.drop_index(op.f('ix_tbl_medicine_requests_clinic_id'), table_name='tbl_medicine_requests')
    op.drop_table('tbl_medicine_requests')
    op.drop_index(op.f('ix_tbl_doctor_availability_id'), table_name='tbl_doctor_availability')
    op.drop_index(op.f('ix_tbl_doctor_availability_doctor_id'), table_name='tbl_doctor_availability')
    op.drop_index(op.f('ix_tbl_doctor_availability_clinic_id'), table_name='tbl_doctor_availability')
    op.drop_table('tbl_doctor_availability')
    op.drop_index(op.f('ix_tbl_appointments_receptionist_id'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_patient_id'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_id'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_doctor_id'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_date'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_created_by'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_clinic_id'), table_name='tbl_appointments')
    op.drop_index(op.f('ix_tbl_appointments_booking_reference'), table_name='tbl_appointments')
    op.drop_index('ix_appointments_clinic_date_time', table_name='tbl_appointments')
    op.drop_table('tbl_appointments')
    op.drop_index(op.f('ix_tbl_user_roles_user_id'), table_name='tbl_user_roles')
    op.drop_index(op.f('ix_tbl_user_roles_role_id'), table_name='tbl_user_roles')
    op.drop_index(op.f('ix_tbl_user_roles_id'), table_name='tbl_user_roles')
    op.drop_table('tbl_user_roles')
    op.drop_index(op.f('ix_tbl_receptionists_user_id'), table_name='tbl_receptionists')
    op.drop_index(op.f('ix_tbl_receptionists_id'), table_name='tbl_receptionists')
    op.drop_index(op.f('ix_tbl_receptionists_email'), table_name='tbl_receptionists')
    op.drop_index(op.f('ix_tbl_receptionists_clinic_id'), table_name='tbl_receptionists')
    op.drop_table('tbl_receptionists')
    op.drop_index(op.f('ix_tbl_patients_user_id'), table_name='tbl_patients')
    op.drop_index(op.f('ix_tbl_patients_phone'), table_name='tbl_patients')
    op.drop_index(op.f('ix_tbl_patients_medical_record_number'), table_name='tbl_patients')
    op.drop_index(op.f('ix_tbl_patients_id'), table_name='tbl_patients')
    op.drop_index(op.f('ix_tbl_patients_cnic'), table_name='tbl_patients')
    op.drop_index(op.f('ix_tbl_patients_clinic_id'), table_name='tbl_patients')
    op.drop_table('tbl_patients')
    op.drop_index(op.f('ix_tbl_inventory_movements_stock_id'), table_name='tbl_inventory_movements')
    op.drop_index(op.f('ix_tbl_inventory_movements_id'), table_name='tbl_inventory_movements')
    op.drop_table('tbl_inventory_movements')
    op.drop_index(op.f('ix_tbl_doctors_user_id'), table_name='tbl_doctors')
    op.drop_index(op.f('ix_tbl_doctors_name'), table_name='tbl_doctors')
    op.drop_index(op.f('ix_tbl_doctors_medical_registration_number'), table_name='tbl_doctors')
    op.drop_index(op.f('ix_tbl_doctors_id'), table_name='tbl_doctors')
    op.drop_index(op.f('ix_tbl_doctors_email'), table_name='tbl_doctors')
    op.drop_index(op.f('ix_tbl_doctors_clinic_id'), table_name='tbl_doctors')
    op.drop_table('tbl_doctors')
    op.drop_index(op.f('ix_tbl_audit_logs_id'), table_name='tbl_audit_logs')
    op.drop_table('tbl_audit_logs')
    op.drop_index(op.f('ix_tbl_audit_deletions_id'), table_name='tbl_audit_deletions')
    op.drop_table('tbl_audit_deletions')
    op.drop_index(op.f('ix_tbl_attachments_id'), table_name='tbl_attachments')
    op.drop_table('tbl_attachments')
    op.drop_index(op.f('ix_tbl_admins_user_id'), table_name='tbl_admins')
    op.drop_index(op.f('ix_tbl_admins_id'), table_name='tbl_admins')
    op.drop_index(op.f('ix_tbl_admins_email'), table_name='tbl_admins')
    op.drop_index(op.f('ix_tbl_admins_clinic_id'), table_name='tbl_admins')
    op.drop_table('tbl_admins')
    op.drop_index(op.f('ix_tbl_users_role_id'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_id'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.drop_table('tbl_users')
    op.drop_index(op.f('ix_tbl_system_preferences_key'), table_name='tbl_system_preferences')
    op.drop_index(op.f('ix_tbl_system_preferences_id'), table_name='tbl_system_preferences')
    op.drop_index(op.f('ix_tbl_system_preferences_clinic_id'), table_name='tbl_system_preferences')
    op.drop_table('tbl_system_preferences')
    op.drop_index(op.f('ix_tbl_role_permissions_role_id'), table_name='tbl_role_permissions')
    op.drop_index(op.f('ix_tbl_role_permissions_permission_id'), table_name='tbl_role_permissions')
    op.drop_index(op.f('ix_tbl_role_permissions_id'), table_name='tbl_role_permissions')
    op.drop_table('tbl_role_permissions')
    op.drop_index(op.f('ix_tbl_inventory_stock_medicine_id'), table_name='tbl_inventory_stock')
    op.drop_index(op.f('ix_tbl_inventory_stock_id'), table_name='tbl_inventory_stock')
    op.drop_index(op.f('ix_tbl_inventory_stock_clinic_id'), table_name='tbl_inventory_stock')
    op.drop_index('ix_inventory_stock_clinic_medicine', table_name='tbl_inventory_stock')
    op.drop_table('tbl_inventory_stock')
    op.drop_index(op.f('ix_tbl_service_codes_id'), table_name='tbl_service_codes')
    op.drop_index(op.f('ix_tbl_service_codes_code'), table_name='tbl_service_codes')
    op.drop_table('tbl_service_codes')
    op.drop_index(op.f('ix_tbl_roles_name'), table_name='tbl_roles')
    op.drop_index(op.f('ix_tbl_roles_id'), table_name='tbl_roles')
    op.drop_table('tbl_roles')
    op.drop_index(op.f('ix_tbl_plans_id'), table_name='tbl_plans')
    op.drop_table('tbl_plans')
    op.drop_index(op.f('ix_tbl_permissions_name'), table_name='tbl_permissions')
    op.drop_index(op.f('ix_tbl_permissions_id'), table_name='tbl_permissions')
    op.drop_table('tbl_permissions')
    op.drop_index(op.f('ix_tbl_medicines_id'), table_name='tbl_medicines')
    op.drop_index(op.f('ix_tbl_medicines_generic_name'), table_name='tbl_medicines')
    op.drop_index(op.f('ix_tbl_medicines_brand_name'), table_name='tbl_medicines')
    op.drop_index('ix_medicines_brand_strength', table_name='tbl_medicines')
    op.drop_table('tbl_medicines')
    op.drop_index(op.f('ix_tbl_clinics_parent_id'), table_name='tbl_clinics')
    op.drop_index(op.f('ix_tbl_clinics_name'), table_name='tbl_clinics')
    op.drop_index(op.f('ix_tbl_clinics_id'), table_name='tbl_clinics')
    op.drop_index(op.f('ix_tbl_clinics_email'), table_name='tbl_clinics')
    op.drop_index(op.f('ix_tbl_clinics_code'), table_name='tbl_clinics')
    op.drop_table('tbl_clinics')
    # ### end Alembic commands ###
